### ISSUE TITLE
Bradley extension is miss version and miss add-ons

### ISSUE THREAD

**Issue by mac4kent** [Gerstmann-Bradley/Bradley-Presets-Add-on#4]
Your add-ons still version 1.1 and I read said 2.2 make me confused.
Would you like upload into Extension for Blender 4.2 and up please.
Thanks.

by Kent Davis

**Comment by Gerstmann-Bradley** [comment]
Addon and Presets are of different version numbers.
Addon is mostly at 1.1 and itself won't be updated for a very long time imo.

Presets are always up to date. For blender 4.3, presets are version 2.3, etc.
Presets are automatically matched to your blender version if you are using the addon.
I hope it clears your confusions.

**Comment by mac4kent** [comment]
May I have version 2.3? I have blender 4.3.1

**Comment by Gerstmann-Bradley** [comment]
>Presets are automatically matched to your blender version if you are using the addon.

If you are using the add-on. It's already 2.3.
if you want to manually download it, you can find it in respective folder at https://github.com/Gerstmann-Bradley/Mograph-Presets-of-Geometry-Nodes/tree/main

**Comment by mac4kent** [comment]
I already have 2.2 but I did not find 2.3. let me click link.

**Comment by mac4kent** [comment]
I got from your link and I never see that one before. I start save webloc. Many thanks.

**Comment by Gerstmann-Bradley** [comment]
> I already have 2.2 but I did not find 2.3. let me click link.

There's no way to really distinguish if you are using 2.2 or 2.3 from users.
and again,
>**Presets are automatically matched to your blender version if you are using the addon.**

I highly doubt you are using 2.2 in blende 4.3 with the add-on.

Most users are not using that links and are not supposed to find the previous link.

**Comment by mac4kent** [comment]
allright no problem.

**Comment by mac4kent** [comment]
I am start work on Flame Fire for Blender 4.3.1 with Bradley 2.3
